### PR TITLE
Add Ui.png to README

### PR DESCRIPTION
**Pull request by pongzers**

### CODE REVIEW

**Review by zhaolingshan — COMMENTED** [review]
LGTM

**Review by augustinekau — APPROVED** [review]
GOOOODD

**Review by kunnan97 — APPROVED** [review]
Excellent, lgtm

**Review by xyzhangg — APPROVED** [review]
Very nice

**Review by zhaolingshan — APPROVED** [review]
NICE

**Review by kunnan97 — APPROVED** [review]
LGTM

**Pull request merged**
